name: Set up environment
description: Sets up Node.js, pnpm, Nx cache, and installs dependencies

inputs:
  cache-key-suffix:
    description: Suffix for the Nx cache key (e.g. job name)
    required: false
    default: default

runs:
  using: composite
  steps:
    - name: Restore Nx cache
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-${{ runner.os }}-${{ inputs.cache-key-suffix }}-${{ github.sha }}
        restore-keys: |
          nx-${{ runner.os }}-${{ inputs.cache-key-suffix }}-

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: pnpm

    - name: Enable Corepack (pnpm)
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        NX_REJECT_UNKNOWN_LOCAL_CACHE: '0'
