name: "Setup Environment"
description: "Sets up Node.js and installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "20"
        cache: "npm"

    - name: Install deps
      run: npm ci
      shell: bash
