packages:
  - 'proto'
  - 'lib'
  - 'functions'
  - 'web'
  - 'e2e-tests'

catalogs:
  default:
    firebase-admin: 12.1.0
    firebase-functions: ^6.6.0
    immutable: ^4.3.6
    protobufjs: ^7.3.2
    selenium-webdriver: ^4.19.0

  dev:
    '@angular/cli': ^20.3.14
    '@bufbuild/buf': ^1.32.2
    '@eslint/eslintrc': ^3.3.3
    '@types/jasmine': ~5.1.0
    '@types/node': ^20.19.27
    '@types/selenium-webdriver': ^4.1.22
    '@typescript-eslint/eslint-plugin': ^8.50.1
    '@typescript-eslint/parser': ^8.50.1
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.29.0
    eslint-plugin-n: ^17.0.0
    eslint-plugin-prettier: ^5.5.4
    firebase-tools: ^14.0.0
    gts: ^7.0.0
    jasmine: ~5.1.0
    jasmine-expect: ^5.0.0
    jasmine-spec-reporter: ^7.0.0
    nx: 22.2.1
    prettier: ^3.7.4
    protobufjs-cli: ^1.1.2
    start-server-and-test: ^2.0.3
    tslib: ^2.8.1
    ts-mocha: ^10.1.0
    ts-node: ^10.9.2
    typescript: ~5.9.0
