packages:
  - 'e2e-tests'
  - 'functions'
  - 'lib'
  - 'proto'
  - 'web'

catalogs:
  default:
    '@angular/animations': ^20.3.15
    '@angular/cdk': ^20.2.14
    '@angular/common': ^20.3.15
    '@angular/compiler': ^20.3.16
    '@angular/core': ^20.3.15
    '@angular/fire': ^20.0.1
    '@angular/forms': ^20.3.15
    '@angular/google-maps': ^20.2.14
    '@angular/localize': ^20.3.15
    '@angular/material': ^20.2.14
    '@angular/material-experimental': ^20.2.14
    '@angular/platform-browser': ^20.3.15
    '@angular/platform-browser-dynamic': ^20.3.15
    '@angular/router': ^20.3.15
    '@babel/runtime': ^7.24.7
    '@fast-csv/format': ^4.3.5
    '@google-cloud/firestore': ^7.7.0
    '@grpc/grpc-js': ^1.10.9
    '@iplab/ngx-file-upload': ^20.0.1
    '@terraformer/wkt': 2.1.2
    angularx-qrcode: ^20.0.0
    busboy: 1.5.0
    cookie-parser: ^1.4.6
    cors: 2.8.5
    firebase: ^10.12.2
    firebase-admin: 12.1.0
    firebase-functions: ^6.6.0
    geojson: 0.5.0
    google-auth-library: 6.1.3
    googleapis: 64.0.0
    http-status-codes: 1.4.0
    immutable: ^4.3.6
    jsonstream-ts: 1.3.6
    long: ^5.2.3
    marked: ^14.1.0
    module-alias: ^2.2.2
    ngx-autosize-input: ^20.0.5
    ngx-color: ^10.1.0
    nodemailer: ^7.0.11
    protobufjs: ^7.3.2
    rxjs: ^7.8.2
    sanitize-html: ^2.13.1
    selenium-webdriver: ^4.19.0
    zone.js: ^0.15.0

  dev:
    '@angular-devkit/build-angular': ^20.3.13
    '@angular-devkit/core': ^20.3.13
    '@angular-eslint/builder': ^20.7.0
    '@angular-eslint/eslint-plugin': ^20.7.0
    '@angular-eslint/eslint-plugin-template': ^20.7.0
    '@angular-eslint/template-parser': ^20.7.0
    '@angular/cli': ^20.3.14
    '@angular/compiler-cli': ^20.3.15
    '@angular/language-service': ^20.3.15
    '@bufbuild/buf': ^1.32.2
    '@eslint/eslintrc': ^3.3.3
    '@jridgewell/source-map': ^0.3.2
    '@nx/angular': ^22.2.1
    '@types/busboy': ^1.5.0
    '@types/cookie-parser': ^1.4.4
    '@types/cors': 2.8.12
    '@types/geojson': ^7946.0.14
    '@types/google.maps': ^3.54.10
    '@types/jasmine': ~5.1.0
    '@types/node': ^20.19.27
    '@types/nodemailer': ^6.4.16
    '@types/sanitize-html': ^2.13.0
    '@types/selenium-webdriver': ^4.1.22
    '@types/source-map-support': ^0.5.10
    '@types/terraformer__wkt': 2.0.0
    '@types/webpack-env': ^1.15.3
    '@typescript-eslint/eslint-plugin': ^8.50.1
    '@typescript-eslint/parser': ^8.50.1
    cpx: ^1.5.0
    diff: ^8.0.3
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.29.0
    eslint-plugin-n: ^17.0.0
    eslint-plugin-prettier: ^5.5.4
    firebase-functions-test: ^3.3.0
    firebase-tools: ^14.0.0
    form-data-encoder: ^4.0.2
    formdata-node: ^6.0.3
    gts: ^7.0.0
    isolate-package: ^1.18.0
    jasmine: ~5.1.0
    jasmine-expect: ^5.0.0
    jasmine-spec-reporter: ^7.0.0
    karma: ^6.4.4
    karma-chrome-launcher: ~3.2.0
    karma-coverage: ~2.2.1
    karma-jasmine: ~5.1.0
    karma-jasmine-html-reporter: ^2.1.0
    mock-cloud-firestore: ^0.12.0
    nx: 22.2.1
    picocolors: ^1.1.1
    prettier: ^3.7.4
    protobufjs-cli: ^1.1.2
    puppeteer: ^24.10.0
    source-map-support: ^0.5.21
    start-server-and-test: ^2.0.3
    ts-mocha: ^10.1.0
    ts-node: ^10.9.2
    tslib: ^2.8.1
    typescript: ~5.9.0
