/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LocationOfInterest {
  jobId: string;
  customId?: string;
  geometry: {
    [k: string]: unknown;
  };
  properties?: {
    [k: string]: unknown;
  };
  submissionCount?: number;
  [k: string]: unknown;
}
