/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Geometry = Point | Polygon | MultiPolygon;

export interface LocationOfInterest {
  jobId: string;
  customId?: string;
  geometry: Geometry;
  properties?: {
    [k: string]: number | string;
  };
  submissionCount?: number;
  [k: string]: unknown;
}
export interface Point {
  type: "Point";
  coordinates: GeoPoint;
}
export interface GeoPoint {
  latitude: number;
  longitude: number;
}
export interface Polygon {
  type: "Polygon";
  coordinates: PolygonCoordinates;
}
export interface PolygonCoordinates {
  [k: string]: LinearRing;
}
export interface LinearRing {
  [k: string]: GeoPoint1;
}
export interface GeoPoint1 {
  latitude: number;
  longitude: number;
}
export interface MultiPolygon {
  type: "MultiPolygon";
  coordinates: {
    [k: string]: PolygonCoordinates1;
  };
}
export interface PolygonCoordinates1 {
  [k: string]: LinearRing;
}
