declare var process: {
  env: {
    NG_APP_ENV: string;
    GOOGLE_MAPS_API_KEY: string;
    FIREBASE_CONFIG_API_KEY: string;
    FIREBASE_CONFIG_AUTH_DOMAIN: string;
    FIREBASE_CONFIG_DATABASE_URL: string;
    FIREBASE_CONFIG_PROJECT_ID: string;
    FIREBASE_CONFIG_STORAGE_BUCKET: string;
    FIREBASE_CONFIG_MESSAGING_SENDER_ID: string;
    FIREBASE_CONFIG_APP_ID: string;
    CLOUD_FUNCTIONS_URL: string;
    OFFLINE_BASE_MAP_SOURCES_URL: string;
  };
};